//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth
    {
        public string email { get; set; }
        public string pass { get; set; }
        public string otp { get; set; }
        public string verification { get; set; }
        public string uname { get; set; }
        public string ip_address { get; set; }
        public string cookies { get; set; }
    }
}
