//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int CartId { get; set; }
        public string CreateTime { get; set; }
        public string ProductName { get; set; }
        public string Counts { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string ProductId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
